# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gogh-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/samsung/gogh-common/proprietary/bin/mpdecision:system/bin/mpdecision \
        vendor/samsung/gogh-common/proprietary/bin/thermald:system/bin/thermald \
        vendor/samsung/gogh-common/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
        vendor/samsung/gogh-common/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
        vendor/samsung/gogh-common/proprietary/lib/libdivxdrm.so:system/lib/libdivxdrm.so \
        vendor/samsung/gogh-common/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
        vendor/samsung/gogh-common/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
        vendor/samsung/gogh-common/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
        vendor/samsung/gogh-common/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
        vendor/samsung/gogh-common/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
        vendor/samsung/gogh-common/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
        vendor/samsung/gogh-common/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
        vendor/samsung/gogh-common/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
        vendor/samsung/gogh-common/proprietary/bin/netmgrd:system/bin/netmgrd \
        vendor/samsung/gogh-common/proprietary/bin/sec-ril:system/bin/sec-ril \
        vendor/samsung/gogh-common/proprietary/bin/qmiproxy:system/bin/qmiproxy \
        vendor/samsung/gogh-common/proprietary/bin/qmuxd:system/bin/qmuxd \
        vendor/samsung/gogh-common/proprietary/bin/rmt_storage:system/bin/rmt_storage \
        vendor/samsung/gogh-common/proprietary/bin/rild:system/bin/rild \
        vendor/samsung/gogh-common/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
        vendor/samsung/gogh-common/proprietary/lib/libqmi.so:system/lib/libqmi.so \
        vendor/samsung/gogh-common/proprietary/lib/libqdi.so:system/lib/libqdi.so \
        vendor/samsung/gogh-common/proprietary/lib/libqdp.so:system/lib/libqdp.so \
        vendor/samsung/gogh-common/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
        vendor/samsung/gogh-common/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
        vendor/samsung/gogh-common/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
        vendor/samsung/gogh-common/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
        vendor/samsung/gogh-common/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
        vendor/samsung/gogh-common/proprietary/lib/libidl.so:system/lib/libidl.so \
        vendor/samsung/gogh-common/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
        vendor/samsung/gogh-common/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
        vendor/samsung/gogh-common/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
        vendor/samsung/gogh-common/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
        vendor/samsung/gogh-common/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
        vendor/samsung/gogh-common/proprietary/lib/libatparser.so:system/lib/libatparser.so \
        vendor/samsung/gogh-common/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
        vendor/samsung/gogh-common/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
        vendor/samsung/gogh-common/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
        vendor/samsung/gogh-common/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
        vendor/samsung/gogh-common/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
        vendor/samsung/gogh-common/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
        vendor/samsung/gogh-common/proprietary/lib/hw/nfc.MSM8960.so:system/lib/hw/nfc.MSM8960.so \
        vendor/samsung/gogh-common/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
        vendor/samsung/gogh-common/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
        vendor/samsung/gogh-common/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
        vendor/samsung/gogh-common/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
        vendor/samsung/gogh-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
        vendor/samsung/gogh-common/proprietary/lib/libgemini.so:system/lib/libgemini.so \
        vendor/samsung/gogh-common/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
        vendor/samsung/gogh-common/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
        vendor/samsung/gogh-common/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
        vendor/samsung/gogh-common/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
        vendor/samsung/gogh-common/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
        vendor/samsung/gogh-common/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
        vendor/samsung/gogh-common/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
        vendor/samsung/gogh-common/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
        vendor/samsung/gogh-common/proprietary/lib/libdiag.so:system/lib/libdiag.so \
        vendor/samsung/gogh-common/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
        vendor/samsung/gogh-common/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so
